#
###################################
# Site wide configuration
####################################
#
title: 何俊秋个人博客
email: xiaohe918@vip.qq.com
description: hejunqiu's blog, powered by jekyll.
url: https://CUITCHE.github.io # the base hostname & protocol for your site
keywords: ["Programming", "iOS", "[C]/Swift", "C/C++", "Blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Beijing
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: hejunqiu
  avatar: avatar.jpg
  job: "iOS Developer"
  bio: "iOS Research & Developer in Beijing, China."
  email: xiaohe918@vip.qq.com
  disqus-shortname: #username
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: CUITCHE #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
